### ISSUE TITLE
Small error in glicko2 implementation

### ISSUE THREAD

**Issue by kiwec** [online-go/goratings#40]
https://github.com/online-go/goratings/blob/50b5443b73daae64306e256205eabee8f4815c65/goratings/math/glicko2.py#L136

Should be `fC * fB <= 0` according to the paper's step 5.

http://www.glicko.net/glicko/glicko2.pdf page 3:

> If fCfB ≤ 0, then set A ← B and fA ← fB; otherwise, just set fA ← fA/2.

**Comment by anoek** [comment]
Good catch!
